# -*- coding: utf-8 -*-
"""tic-tac-toe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WayKo-LoOwtAn1LeYOWCJB1bGxd0qqEe
"""

board = [["-","-","-"], ["-","-","-"], ["-","-","-"]]

print("    0    1    2")
count = 0
for row in board:
    print(count, row)
    count += 1

