# -*- coding: utf-8 -*-
"""tic-tac-toe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WayKo-LoOwtAn1LeYOWCJB1bGxd0qqEe
"""

game = [["-","-","-"],
        ["-","-","-"],
        ["-","-","-"]]


def print_board():
    print("    0    1    2")
    for count, row in enumerate(game):
        print(count, row)



def win():
  for row in game:
    column_1 = row[0]
    column_2 = row[1]
    column_3 = row[2]
    if column_1 == column_2 == column_3 and column_1 != "-":
      if column_1 == "X":
        print("Player One Wins!")
        return True
      if column_1 == "O":
        print("Player Two Wins!")
        return True
  for i in range (0,3):
    if game[0][i] == game[1][i] == game[2][i] and game[0][i] !="-":
      if game[0][i] == "X":
        print("Player One Wins!")
        return True
      if game[0][i] == "O":
        print("Player Two Wins!")
        return True
  if game[0][0] == game[1][1] == game[2][2] and game[0][0] != "-":
    if game[0][0] == "X":
      print("Player One Wins!")
      return True
    if game[0][0] == "O":
      print("Player Two Wins!")
      return True
  if game[2][0] == game[1][1] == game[0][2] and game[2][0] != "-":
    if game[2][0] == "X":
      print("Player One Wins!")
      return True
    if game[2][0] == "O":
      print("Player Two Wins!")
      return True



print("Welcome to Tic-Tac-Toe")
print_board()
i=1
while i < 10:
  print("turn",i)
  if i % 2 == 1:
    print("Player One, it's your turn")
    c= int(input("player 1, enter column: "))
    if c < 0 or c > 2:
      print("invalid column")
      continue
    r= int(input("enter row: "))
    if r < 0 or c > 2:
      print("invalid row")
      continue
    if game[r][c] == "-":
      game[r][c] = "X"
    else:
      print("there is already a marker at ", c, ", ", r, " try again")
      continue
    print_board()
  if i % 2 == 0:
    print("Player Two, it's your turn")
    c= int(input("player 2, enter column: "))
    if c < 0 or c > 2:
      print("invalid column")
      continue
    r= int(input("enter row: "))
    if r < 0 or c > 2:
      print("invalid row")
      continue
    if game[r][c] == "-":
      game[r][c] = "O"
    else:
      print("there is already a marker at ", c, ", ", r, " try again")
      continue
    print_board()
  if win()==True or i == 9:
    playagain = input("Would you like to play again? Input 'y' to continue or enter to end game.\n")
    if playagain == 'y':
      game = [["-","-","-"],["-","-","-"],["-","-","-"]]
      i=1
      continue
    else:
      print("Goodbye")
      break
  i += 1