# -*- coding: utf-8 -*-
"""tic-tac-toe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WayKo-LoOwtAn1LeYOWCJB1bGxd0qqEe
"""

game = [["-","-","-"],
        ["-","-","-"],
        ["-","-","-"]]


def print_board():
    print("    0    1    2")
    for count, row in enumerate(game):
        print(count, row)
print("Welcome to Tic-Tac-Toe")
print_board()
i=1
while i < 10:
  print("turn",i)
  if i % 2 == 1:
    print("Player One, it's your turn")
    c= int(input("player 1, enter column: "))
    if c < 0 or c > 2:
      print("invalid column")
      continue
    r= int(input("enter row: "))
    if r < 0 or c > 2:
      print("invalid row")
      continue
    if game[r][c] == "-":
      game[r][c] = "X"
    else:
      print("there is already a marker at ", c, ", ", r, " try again")
      continue
    print_board()
  if i % 2 == 0:
    print("Player Two, it's your turn")
    c= int(input("player 2, enter column: "))
    if c < 0 or c > 2:
      print("invalid column")
      continue
    r= int(input("enter row: "))
    if r < 0 or c > 2:
      print("invalid row")
      continue
    if game[r][c] == "-":
      game[r][c] = "O"
    else:
      print("there is already a marker at ", c, ", ", r, " try again")
      continue
    print_board()
  i += 1